### ISSUE TITLE
Catalog gridding - Differenene in the outcome of gridding of test catalog

### ISSUE THREAD

**Issue by khawajasim** [SCECcode/pycsep#86]
I was trying to repeate the results of the global forecasting testing experiment from a forecast from previous paper. I was using my own catalog gridding function. And in the end, I used a mock class to interface the data (gridded catalog, gridded forecast) with toolkit to run the poission consistency tests. I was unable to get the same results.

So I dug a bit deeper. I found that the spatial counts (spatial gridding) obtained from the toolkit were different as that yielded  by my function. I tried to locate the difference. But apparently, it was working fine on my side. And I also tried to look into pycsep code. But I was unable to follow it. However, I am certain that this issue is due to boundary events.

I am sharing here a link with files and code that provides different gridded catalog. Can you please help me locate where the error is coming from? Is it due to some unnoticed typo my side or some rounding off error in the toolkit? I am looking for an external opinion about this.

The files on the link are:
1- Testing Catalog (2014-2019).
2- Toolkit_grid : Global testing grid obtained from toolkt
3- Toolkit_gridded_cat : Spatial gridded counts obtained from toolkit for the above grid.
4- Python script that I used to acquire my gridded spatial rates for grid of (2). And compared it with spatial counts of (3).
 
https://drive.google.com/drive/folders/1rnIuX9Bqwg95BMhwKIQ23sP8ld4q95PU?usp=sharing

**Comment by khawajasim** [comment]
I think I updated my repo in past 2-3 weeks. 

I am certain that this is the same catalog. The total numbe of events also verify this. 

Yes, the grid is coming from the forecast (Tono's forecast). But I just acquired the same grid and corresponding spatial counts., in order to make sure that the arrangement of the grid remains same for comparision.

**Comment by wsavran** [comment]
can you elaborate a bit more on where you found the different items here? specifically, items (2) and items (3)? i dont believe these files are included in the toolkit. if they are can you please point me to the functions that you used to obtain them? 

also, if possible is there a way to reduce this problem to a more simple form that doesn't include several hundred megabytes of data files? for example, maybe we can figure out exactly where the discrepancies originate. do we have an idea of how many of these are different?

**Comment by wsavran** [comment]
can you rerun your calculations using the most up-to-date code available in the repository, and try and replicate the example in a single script that performs the gridding from the toolkit without reading in a gridded catalog file?

**Comment by khawajasim** [comment]
First I am responding to your queries, then later on as I progress, I would share further updates. 

The item 2 and 3 are coming from the following steps (code lines):

fore = GriddedForecast.from_custom(read_tono_format, name=name, func_args=(fname, area_fname, mws))
    # bind region from forecast to catalog
    cat.region = fore.region
    grid = cat.region.origins() #----[item 2]
    
    gridded_cat = cat.spatial_counts() #----[item 3]
    
   So, I take this grid [item 2]. Because I want to make sure I have the right ordered grid. I believe that order matters here, so I am a bit careful, so that I can compare the results.
   
   When I use this grid [item 2], and use my own function (provided in folder) to perform catalog gridding, Then ideally it should exactly match the item 3. But I found out that somewhere the boundary events are recorded in different cells in  both codes. 

PS: I round off grid every time to 1 decimal place, because I think I should do it for being on safe side. We know that global starts from -180 (NOT from -180.00001), and goes on by -180.1..... Rounding off will eliminate the potential errors caused by -180.0001.

Final results surely change (little) when spatial gridding is different.

I can send the mock class, but comes after it. I load gridded data into using mock class. So first lets sort out this.
 
As soon as I make some progress in further narrowing down this, I shall write. 

Cheers

**Comment by wsavran** [comment]
thanks for clarifying a lot of those points for me. ill look into the script you sent me. 

also can you try the gridded without rounding, because that wasn’t performed previously. since the grid came from the forecast, it was treated as it was in the forecast.

if we can narrow down, say, the lat/lon of the points that are different, and the spatial extents of the grids that would be a big first step to figuring this out.

**Comment by khawajasim** [comment]
Hi,

For now, I traced a few differences to some earthquakes. Although, there are a lot of other differences. But for starting, can you perform gridding on these few earthquakes for the mentioned 0.1x0.1 grid and see whether earthquakes are going to the cells as intended?


id | year | lat | lon | depth | mag
-- | -- | -- | -- | -- | --

43628 | 2015 | -15.88 | -178.6 | 10 | 6.47299491795823

48129 | 2017 | 51.75 | -178.6 | 13 | 6.20908999813237

49778 | 2018 | -30.61 | -178.02 | 34.5 | 6.04742743401892

41655 | 2014 | -29.98 | -177.73 | 20 | 6.87986039073757


50292 | 2019 | -30.6 | -177.79 | 10 | 6.47123868634588


I updated the package yesterday, so it should be fine now. I believe, grid rounding should be done by default in the toolkit. Since for now whoever tests the forecasts, its not intended for 2nd or 3rd decimal place. Would you agree?

Cheers,

**Comment by khawajasim** [comment]
closed by mistake...

**Comment by wsavran** [comment]
thanks for tracking this down. do you know what % of the events were placed into the wrong cells? 

it would be helpful if you were able to write a script that can performs the binning using your function and the pyCSEP function side-by-side in the same script without changing the grid. then, we can track down the events that are different and compare their lat/lon and the lat/lon of the cells. 

ideally we can turn the outcome of this into another unit/acceptance test to make sure that the code is performing how we expect.

are the eqs you linked in the previous message binned using your rounded grid?

i'm not sure that i believe that grid rounding should occur at all. once we get this issue sorted, we can discuss that point. maybe that is something we want to add, but we need to figure this issue out first.

i'm a bit surprised that these events are the ones that are mislabeled, because only a couple of them are actually lying on the boundary between two cells.


also, if you use that id to look up the lat/lon what do you find?

**Comment by khawajasim** [comment]
Hi,
I may have wrongly picked the following two:
49778 | 2018 | -30.61 | -178.02 | 34.5 | 6.04742743401892

41655 | 2014 | -29.98 | -177.73 | 20 | 6.87986039073757

As I was tracing it manually. and had no record. There are some issues without rounding off as well. Though, I will not be surprised I am doing it wrong.

Can you provide me the your gridding code as a separate script, so that I can compare them side by side? Just to make sure that I do not mix up /mess up things while extracting gridding code. 

For now, I have called off the day, but I shall do this first thing on monday.

Cheers,

**Comment by wsavran** [comment]
```
I may have wrongly picked the following two:
49778 | 2018 | -30.61 | -178.02 | 34.5 | 6.04742743401892

41655 | 2014 | -29.98 | -177.73 | 20 | 6.87986039073757

As I was tracing it manually. and had no record.
```
do you mean that these points were binned correctly and the others are still wrong? when we are tracking down these issues i think we want to try and do everything programmatically. ultimately i want to see the script that produces the error and be able to run it without modification on my machine and reproduce the error.

i would recommend binning using some lower-level functions provided in pycsep. i think we should try and replicate this bug in a single script without reading in files that are tough to trace. the only input files should be the grid origins and the catalog. 

i'm going to start the script for you. can you complete it with the code you wrote and some additional comparisons below to identify the differences? we want to know the lat/lon of the events that are misplaced and also the coordinates of the bin that are wrong. also understanding what fraction of the events are binned incorrectly would be helpful.

```
from csep.core import regions

# i assume that you have a file that contains the lon/lat pairs of the origin of the grid and they are stored in a numpy array # with shape = (nbins, 2), such that arr[:,0] == lons and arr[:,1] == lats. we can call this array origin_arr.

# you can verify the dh and origins through r.dh and r.origins(). the dh should be automatically parsed from the origin_arr.
# note: the dh in lon and lat needs to be the same. 
r =  regions.CartesianGrid2D.from_origins(origin_arr)

# this low-level function is called when binning a catalog. note: when you add your quadtree work this will need to change, # so we can perform the binning using the same catalog.spatial_counts() call, but using the quadtree region instead of the # cartesian region. just something to think about.
gridded_cat = regions._bin_catalog_spatial_counts(catalog_lons, catalog_lats, r.num_nodes, r.bbox_mask, r.idx_map, r.xs, r.ys)

# you should perform your gridding here

# then compare your asim_gridded_cat against gridded_cat

# another note: you can use the region object to look up the lat/lon of the index in a couple of ways.
# the following will return a list of polygon objects that contain the bad locations
bad_bins = r.get_location_of(bad_indices)

# the following will return a list of the origins 
bad_origins = [p.origin for p in bad_bins]
```

let me know if you have any questions with this.

**Comment by wsavran** [comment]
hi asim, ive let my curiosity take over and i've looked into this a little bit. i think i understand your issue. i've attached a script here that will recreate the bug at the lowest-level in the toolkit. thanks for finding this issue.

ill try and summarize whats going on here. i need to implement these changes into the toolkit and build this as a test-suit, but this issue is caused by the way the `CartesianGrid2D` works. in short, it parses the list of polygons that define the grid and drapes a 2D square grid over these polygons. this allows the list of polygons to include missing cells, be out of order, have an arbitrary shape. 

however, when creating this grid the `np.arange` function appears to introduce some floating point wander which can be seen in the following code. then, i implement a new function that minimizes the drift called clean_range() and show that when using these bounds for the grid, the desired index is recovered. this needs to be directly implemented into the class, but the functionality that would exist is shown in the following code.

```python
from csep import regions
import numpy as np
from decimal import Decimal
from csep.utils.calc import bin1d_vec

def print_decimal(poly, lon, lat):
    print(Decimal(poly.points[1][0]), Decimal(lon), Decimal(poly.points[2][0]))
    print(Decimal(poly.points[0][1]), Decimal(lat), Decimal(poly.points[2][1]))
    print()
    
def print_nice(poly, lon, lat):
    print(poly.points[1][0], lon, poly.points[2][0])
    print(poly.points[0][1], lat, poly.points[2][1])
    print()

g = np.loadtxt('toolkit_grid.csv', delimiter=',')
```
```python
print(g[0,:])
print(g[-1,:])
```
Output:
```
[-180.  -90.]
[ 179.9   89.9]
```
```python
r = regions.CartesianGrid2D.from_origins(g)
grid_lons = g[:,0]
grid_lats = g[:,1]

print(grid_lons.min(), grid_lons.max(), grid_lats.min(), grid_lats.max())
```
Output:
```
-180.0 179.9 -90.0 89.9
```
```python
# test points
lons = np.array([-178.6, -178.6, -178.02, -177.73, -177.79])
lats = np.array([-15.88, -51.75, -30.61, -29.98, -30.6])

# directly compute the indexes from the region object
idxs = r.get_index_of(lons, lats)
for i, idx in enumerate(idxs):
    found_poly = r.polygons[idx]
    lon = lons[i]
    lat = lats[i]
    print_nice(found_poly, lon, lat)
    print_decimal(found_poly, lon, lat)
```
Output:
```
-178.7 -178.6 -178.6
-15.9 -15.88 -15.8

-178.700000000000017053025658242404460906982421875 -178.599999999999994315658113919198513031005859375 -178.6000000000000227373675443232059478759765625
-15.9000000000000003552713678800500929355621337890625 -15.8800000000000007815970093361102044582366943359375 -15.7999999999999918287585387588478624820709228515625

-178.7 -178.6 -178.6
-51.8 -51.75 -51.7

-178.700000000000017053025658242404460906982421875 -178.599999999999994315658113919198513031005859375 -178.6000000000000227373675443232059478759765625
-51.7999999999999971578290569595992565155029296875 -51.75 -51.69999999999998863131622783839702606201171875

-178.1 -178.02 -178.0
-30.7 -30.61 -30.6

-178.1000000000000227373675443232059478759765625 -178.020000000000010231815394945442676544189453125 -178
-30.699999999999999289457264239899814128875732421875 -30.6099999999999994315658113919198513031005859375 -30.599999999999990762944435118697583675384521484375

-177.8 -177.73 -177.7
-30.0 -29.98 -29.9

-177.80000000000001136868377216160297393798828125 -177.729999999999989768184605054557323455810546875 -177.69999999999998863131622783839702606201171875
-30 -29.980000000000000426325641456060111522674560546875 -29.8999999999999914734871708787977695465087890625

-177.8 -177.79 -177.7
-30.7 -30.6 -30.6

-177.80000000000001136868377216160297393798828125 -177.789999999999992041921359486877918243408203125 -177.69999999999998863131622783839702606201171875
-30.699999999999999289457264239899814128875732421875 -30.60000000000000142108547152020037174224853515625 -30.599999999999990762944435118697583675384521484375
```
```python
# implement the binning procedure directly
p = lons[0]
a0 = g[0,0]
h = 0.1

a0_tol = np.abs(a0) * np.finfo(np.float).eps
h_tol = np.abs(h) * np.finfo(np.float).eps
p_tol = np.abs(p) * np.finfo(np.float).eps

idx_lon = int(np.floor((p-a0)/h))
idx_lon_tol = int(np.floor((p + (p_tol + a0_tol) - a0) / (h - h_tol)))

unique_lons = np.unique(g[:,0])
unique_lats = np.unique(g[:,1])

# binning using lons loaded in from grid
idx_lon = int(bin1d_vec(lons[0], unique_lons))
idx_lat = int(bin1d_vec(lats[0], unique_lats))

# exact implementation of the index of function
idx_r = int(bin1d_vec(lons[0], r.xs))
idy_r = int(bin1d_vec(lats[1], r.ys))

# compute diff
abs_diff = np.sum(np.abs(r.xs - unique_lons))

# show diff
print(abs_diff)

# shows index using grid bins
print(idx_lon, idx_lat)

# shows index using region bins
print(idx_r, idy_r)

# grid information
print(r.xs[0], r.xs[-1])
print(r.ys[0], r.ys[-1])
print(r.dh)

# these should be equal
global_ind = int(r.idx_map[idx_lat][idx_lon])
print(global_ind, r.get_index_of(lons[0], lats[0]))

# origin point of the correct grid cell
print(r.polygons[global_ind])
```
Output:
```
5.52431466821e-08
14 741
13 382
-180.0 179.9
-90.0 89.9
0.1
25941 24141
(-178.60000000000002, -15.9)
```
```python
def clean_range(start, end, h):
    """ Returns array holding bin edges that doesn't contain floating point wander.

    Floating point wander can occur when repeatedly adding floating point numbers together. The errors propogate and become worse over the sum. This function generates the 
    values on an integer grid and converts back to floating point numbers through multiplication.

     Args:
        start (float)
        end (float)
        h (float): magnitude spacing

    Returns:
        bin_edges (numpy.ndarray)
    """
    # convert to integers to prevent accumulating floating point errors
    const = 10000
    start = np.floor(const * start)
    end = np.floor(const * end)
    d = const * h
    return np.arange(start, end + d / 2, d) / const

    # build bounding box of set of polygons based on origins (straight from pycsep code)
    nd_origins = np.array([poly.origin for poly in r.polygons])
    bbox = [(np.min(nd_origins[:, 0]), np.min(nd_origins[:, 1])),
    (np.max(nd_origins[:, 0]), np.max(nd_origins[:, 1]))]

    lon_start, lon_end = bbox[0][0], bbox[1][0]
    lat_start, lat_end = bbox[0][1], bbox[1][1]

    clean_lons = clean_range(lon_start, lon_end, h)
    clean_lats = clean_range(lat_start, lat_end, h)

    np.testing.assert_array_almost_equal_nulp(clean_lons, unique_lons)
    np.testing.assert_array_almost_equal_nulp(clean_lats, unique_lats)

    # binning using lons loaded in from grid
    idx_lon = int(bin1d_vec(lons[0], unique_lons))
    idx_lat = int(bin1d_vec(lats[0], unique_lats))

    print(idx_lon, idx_lat)
    print(idx_lon_clean, idx_lat_clean)
```
Output:
```
14 741
14 741
```

**Comment by khawajasim** [comment]
Dear Bill,
Good morning. 

This is indeed a good news to start a day, that we have identified a bug. Thank you for looking into this.I am glad that my find was useful.

I have two queations. 

1. Did you see that now after cleaning of floating point, do the both final gridded catalog match totally with each other?

2. However I was thinking that different gridded catalog should change the testing outcomes? I think the results may shift a little bit overall. What do you say?

**Comment by pabloitu** [comment]
Nice catch guys. I'd be happy to test ASAP if everything is working alright, if you create a branch to try out the changes.

**Comment by wsavran** [comment]
i haven't checked all of the events in the catalog. i was just trying to understand where the differences were occurring. i will push out an update sometime in the next few days to fix this and then i'll ask you to re-run your script again to verify things work.

of course this will affect the calculations of the tests, but the question is more about the magnitude of the differences. i expect this will result in minor differences in evaluation results. all of the previous tests have shown good agreement with previously published results, so from that i wouldn't expect this change would drastically impact the results.

**Comment by wsavran** [comment]
@khawajasim i will include your forecast in the mix when i recompute the results.

**Comment by wsavran** [comment]
hi all, 

the fixes are included in the branch bill-hotfix (this pull request). i have added some simple unit tests that capture the issues that asim noticed. @pabloitu @khawajasim let me know if you're able to pull this branch and run some of your own testing.

**Comment by wsavran** [comment]
@khawajasim i wrote a script to test the binning on the entire catalog using your script and the pycsep function. however, its showing that your function is returning two less events than expected.

```python
```

**Comment by khawajasim** [comment]
Dear Bill,

Thank you for showing this. Lets just say, I was not surprised to see this :). This can be corrected by simply introducing one more line in the code:
-grid_bounds = np.round(grid_bounds,1)

Simply just by rounding up to 1 decimal place, things will be solved. Now lets dis a bit deeper and see what is happening without rounding off in the current code, by considering the 1st instances
(array([3396964, 3396965]),)

grid_bounds[3396964]
Out[379]: array([  8.7, -53.6,   8.8, -53.5])

grid_bounds[3396965]
Out[380]: array([  8.7, -53.5,   8.8, -53.4])

Event in the catalog at i=37 is getting both these cells, which is: 

lat[37]
Out: -53.5

lon[37]
Out: 8.72

So we see that this is a boundary events from Latitude preservative. 
By definition of grid, the event with lat=-53.5 should be falling into the cell grid_bounds[3396965]. And not in the other. Right? The logic that determines this process is:

-llat < grid_bounds[3396964, 3]
-llat < grid_bounds[grid_bounds[3396965, 3]

But because of floating points "llat < grid_bounds[3396964, 3]" is not truly 53.5, rather less than that. 

Decimal(grid_bounds[3396964,3])
Out: Decimal('-53.49999999999999289457264239899814128875732421875').

So when the logic applies here, the outcome is like that :

llat = lat[37]

llat < grid_bounds[3396964,3]
Out: True

llat < grid_bounds[3396965,3]
Out: True

Since Top right corner of the cell is supposed to be -53.5, but it is not actually -53.5. So the above condition was supposed to be False for the cell: grid_bounds[3396964,3]

Now, after introducing the correction, lets see the behaviour now:

llat < round(grid_bounds[3396964,3],1)
Out: False

llat < round(grid_bounds[3396965,3],1)
Out: True

So that is why, I always round off the grid to 1 decimal place before computing the gridded catalog.

**Comment by khawajasim** [comment]
After introducing correction in float points by simply putting np.round(grid_bounds, 1), I got the exactly same gridded catalog with pycsep toolkit and my own function.

Cheers

**Comment by wsavran** [comment]
was this result obtained using the code contained in this bug-fix branch?

**Comment by khawajasim** [comment]
No I simply copied and pasted code in my PC ad run it using the already available version of pyCSEP. I updated pyCSEP repository on last Friday.

**Comment by wsavran** [comment]
interesting, i just ran this and also found no issues between the two methods. pycsep has some logic to account for places where the bins are close. essentially, it accounts for the absolute error in floating point numbers when calculating the grid location. now that we defined these two grids identically, the issues go away. 

the issue noted above with the cartesiangrid should still be addressed.

```python
import csv
import time

import csep
from csep import regions

import numpy as np

def catalog_gridding_cell(grid_bounds,lon,lat,mag):
    """
    ---Iterates over catalog, instead of GRID
    
    Performs gridding on a catalog with respect to Spatial Grids Cells only.
    Does not consider magnitude bins
    
    Parameters
    ----------
    Bounds : nx4D array. origin_Lon_Lat = grid_bound[0:1], TopRight_Lon_Lat = grid_bound[2:3]
        List of Quad Keys strings.
    lat : Array of float
        Latitutde of Observed Catalog.
    lon : Array of float
        Longitude ofObserved Catalog
    mag : Array of float        -----Not needed actually
        Magnitudes of the Observed Catalog

    Returns
    -------

    spatial_grid : Just Global Cells
        list of earthquakes corresponding to each cell

    """
    event_list = [] 
    num = np.zeros(len(grid_bounds))
    #Spatial binning arrangement
    for i in range(len(mag)):
        llat = lat[i]
        llon = lon[i]
        eqs = np.logical_and(np.logical_and(llon>=grid_bounds[:,0], llat>=grid_bounds[:,1]), 
                                np.logical_and(llon<grid_bounds[:,2], llat<grid_bounds[:,3]) ) 
        if np.sum(np.count_nonzero(eqs)) > 1:
            print('Warning: found more than one bin for an earthquake')
            print(np.where(eqs==True))
        num[np.where(eqs==True)] = num[np.where(eqs==True)]+1
    
    return num


def read_asims_catalog(filename):
    with open(filename, 'r') as f:
        eventlist = [row for row in csv.reader(f)]
    return eventlist[1:]

# pycsep stuff
dh = 0.1
t0 = time.time()
grid = np.loadtxt('toolkit_grid.csv', delimiter=',')
grid = np.round(grid,1)
r = regions.CartesianGrid2D.from_origins(grid, dh=dh)
cat = csep.load_catalog('cat_test.csv', loader=read_asims_catalog, region=r)
t1 = time.time()
pycsep_counts = cat.spatial_counts()
t2 = time.time()
print(f"did csep stuff in {t1-t0} seconds. gridding in {t2-t1} seconds.")

# asim stuff
cat_asim = np.loadtxt('cat_test.csv', delimiter=',', skiprows=1)
lat = cat_asim[:,2]
lon = cat_asim[:,3]
mag = cat_asim[:,5]
grid_bounds = np.column_stack((grid, grid+dh))
t0 = time.time()
grid_bounds = np.round(grid_bounds,1)
asim_counts = catalog_gridding_cell(grid_bounds, lon, lat, mag)
t1 = time.time()
print(f"did asim stuff in {t1-t0} seconds.")

py_lats = cat.get_latitudes()
py_lons = cat.get_longitudes()
origins = r.origins()

diff = pycsep_counts - asim_counts
print(np.count_nonzero(diff))
print(cat.event_count, np.sum(pycsep_counts))
print(len(lat), np.sum(asim_counts))
print()

# verify pycsep stuff
print('verifying pycsep stuff')
lats = cat.get_latitudes()
lons = cat.get_longitudes()

idxs = r.get_index_of(lons, lats)
for i, idx in enumerate(idxs):
    found_poly = r.polygons[idx]
    lon = lons[i]
    lat = lats[i]

    try:
        assert lon >= found_poly.points[1][0] and lon < found_poly.points[2][0]
    except AssertionError:
        print(f'error at lon={lon} for point ({lon}, {lat}) with bounds ({found_poly.points[1][0]:.2f}, {found_poly.points[2][0]:.2f})') 

    try:
        assert lat >= found_poly.points[0][1] and lat < found_poly.points[2][1]
    except AssertionError:
        print(f'error at lat={lat} for point ({lon}, {lat}) with bounds ({found_poly.points[0][1]:.2f}, {found_poly.points[2][1]:.2f})') 
```

**Comment by khawajasim** [comment]
Hey Bill,

Please find folder from the link below.

The script in the folder runs three different combinations. 
1- Entirely toolkit for evaluation
2- Use mock class to run test from toolkit
3- Use my gridding function

The difference in catalog gridding is identified. However, the impact on the results is very low. 

https://drive.google.com/drive/folders/1dMlYStJaUZw2Ectb1oiIyvgarC0Dp1Zz?usp=sharing

**Comment by wsavran** [comment]
hi asim, is there a way you can share the expected results from the script? im downloading it now, but id like to know whether we are getting the same results.

**Comment by wsavran** [comment]
@khawajasim i just ran the scripts you shared. here are my outputs
```
Step 1: Use Toolkit Directly for forecast Evaluation

        Name: None

        Start Date: 2014-01-01 00:00:00+00:00
        End Date: 2019-01-01 00:00:00+00:00

        Latitude: (-63.26, 74.39)
        Longitude: (-179.23, 179.66)

        Min Mw: 5.950476922600889
        Max Mw: 8.27271203001144

        Event Count: 651

expected event count before scaling: 116.19988444838295
expected event count after scaling: 697.1993066902971
-4556.39359118
Step 2: Test Mock classes - Run same data & test through MockClass of Asim
-4556.39359118
Mock class is working fine
Step 3: Test Catalog Gridding - Use catalog Gridding of Asim
-4556.39359118
Catalog Gridding is Equal
```

it looks like the changes in the pr solve the problem. we can close this issue with those changes once they are reviewed and approved.

**Comment by khawajasim** [comment]
Hi Bill,

I am sorry I left office at 5:15 today. But if required, I can share the output tomorrow. At my side both grids were not same and the outcome of gridding was different.

It looks like that the new changes you made are effective and outcome is same. Is that right? "Changes in pr", what is meant by "pr" ?

**Comment by khawajasim** [comment]
The LL yielded by your gridding was 4555.3 where as LL yielded by my gridding was 4556.3. Now its good to see that the issue is fixed.

**Comment by wsavran** [comment]
closed by #89
